Support frameworks, build-tools, and add-sources
OS X (darwin) frameworks are picked out from a .cabal file and added to
NIX_LDFLAGS.

Better build-tool support. Build-tools are /only/ passed to expressions
that need them. hsc2hs which is bundled with GHC is now special-cased.

Add-source dependencies that depend on other add-source dependencies now
work properly.

A bug with sandbox timestamp updates in the presence of multiple
add-source dependencies has been fixed.

diff --git a/cabbage b/cabbage
--- a/cabbage
+++ b/cabbage
@@ -1,5 +1,174 @@
 #!/usr/bin/env bash
 
+# Print only the library target portion of a .cabal file and filter
+# out linen comments.
+isolateLibraryTarget() {
+  sed -n '/^[Ll]ibrary/,/^[^[:space:]]/ { /^[[Ll]ibrary/p; /^[[:space:]]/p; }' \
+  | sed 's/--.*$//'
+}
+
+# Remove any Cabal block guarded by an "if os(windows)" or "if
+# os(solaris)" or "if os(ios)" conditional. This is a very fragile
+# test!
+removeWindowsBlocks() {
+  local AWK
+  read -r -d '' AWK<<'EOF'
+BEGIN { windowsIndent = 0; }
+{
+  if(match($0, /if os\(windows\)/)) {
+    windowsIndent = RSTART;
+  } else if(match($0, /if os\(solaris\)/)) {
+    windowsIndent = RSTART;
+  } else if(match($0, /if os\(ios\)/)) {
+    windowsIndent = RSTART;
+  } else if(windowsIndent > 0) {
+    match($0, /^[[:space:]]*/);
+    if(RLENGTH <= windowsIndent) {
+      windowsIndent = 0;
+      print($0);
+    }
+  } else {
+    print($0);
+  }
+}
+EOF
+  awk "$AWK"
+}
+
+# Print the library target of any .cabal file in the current directory
+# while removing any blocks guarded by a windows or solaris check.
+cabalLibraryTarget() {
+  cat ./*.cabal | sed 's/--.*$//' | isolateLibraryTarget | removeWindowsBlocks
+}
+
+# Print each build-tool without any version constraint.
+cabalBuildTools() {
+  cabalLibraryTarget \
+  | grep -i "build-tools" | awk 'BEGIN { FS=":"; } { print($2); }' | sed 's/,/\
+/' | sed -e 's/^[[:space:]]*//' -e 's/ .*$//'
+}
+
+allBuildToolsAux() {
+  cabalBuildTools
+  if [ -d .cabbages ]; then
+    local DEPS=($(getDependencies cabal.config))
+    local d
+    (cd .cabbages && \
+     for d in "${DEPS[@]}"; do
+       (cd "$d" &&  cabalBuildTools)
+     done)
+  fi
+}
+
+# Print the array of all build-tools used to build this package and
+# all its dependencies.
+allBuildTools() {
+  local TOOLS=($(allBuildToolsAux | uniq))
+
+  # hsc2hs comes with GHC
+  local special
+  for special in hsc2hs; do
+    local i=$(findIndex "$special" TOOLS[@])
+    if [ "$i" -gt -1 ]; then
+      unset TOOLS[$i]
+    fi
+  done
+  echo "${TOOLS[@]}"
+}
+
+# Print the array of all buildable build-tools (ie not happy, alex, or
+# hsc2hs) used to build this package and all of its dependencies.
+allBuildableBuildTools() {
+  local TOOLS=($(allBuildToolsAux | uniq))
+
+  # We don't build alex, happy, or hsc2hs
+  local special
+  for special in alex happy hsc2hs; do
+    local i=$(findIndex "$special" TOOLS[@])
+    if [ "$i" -gt -1 ]; then
+      unset TOOLS[$i]
+    fi
+  done
+  echo "${TOOLS[@]}"
+}
+
+cabalFrameworks() {
+  cabalLibraryTarget \
+  | grep -i "frameworks" | awk 'BEGIN { FS=":"; } { print($2); }' | sed 's/,/\
+/' | uniq
+}
+
+unconstrainCabal() {
+  local UNCONSTRAIN
+  read -r -d '' UNCONSTRAIN<<'EOF'
+BEGIN { 
+  buildDep = 0;
+  FS = ",";
+}
+{
+  lineSkip = 0;
+  if(match($0, /^[[:space:]]*[Bb][Uu][Ii][Ll][Dd]-[Dd][Ee][Pp][Ee][Nn][Dd][Ss]:/)) {
+    buildDep = 1;
+    match($0, /^[[:space:]]*/);
+    indentation = RLENGTH;
+    for(i = 0; i < RLENGTH; ++i) printf(" ");
+    printf("build-depends:");
+    sub(/^[[:space:]]*[Bb][Uu][Ii][Ll][Dd]-[Dd][Ee][Pp][Ee][Nn][Dd][Ss]:/,"",$0);
+    match($0, /^[[:space:]]*/);
+    for(i = 0; i < RLENGTH; ++i) printf(" ");
+    sub(/^[[:space:]]*/,"",$0);
+  } else if(buildDep) {
+    if(match($0,/^[[:space:]]*$/)) {
+      lineSkip = 1;
+    } else {
+      match($0, /^[[:space:]]*/);
+      if(RLENGTH <= indentation) {
+        buildDep = 0;
+      } else {
+        for(i = 0; i < RLENGTH; ++i) printf(" ");
+        sub(/^[[:space:]]*/,"",$0);
+      }
+    }
+  }
+  if(buildDep && !lineSkip) {
+    # Update a line of a build-depend
+    for(i = 1; i <= NF; ++i) {
+      sub(/^[[:space:]]*/,"",$(i));
+      sub(/[[:space:]]*$/,"",$(i));
+      if(match($(i), "[ ><=]")) {
+        pkgName = substr($(i), 1, RSTART - 1);
+        printf("%s", pkgName);
+      } else {
+        printf("%s", $(i));
+      }
+      if(i < NF) printf(", ");
+    }
+    printf("\n");
+  } else {
+    # Everything else gets printed
+    print $0
+  }
+}
+EOF
+  awk "$UNCONSTRAIN"
+}
+
+# Try freezing after removing all version constraints.
+freezeUnconstrained() {
+ local NUMCABALS=$(find . -maxdepth 1 -name '?*.cabal' | wc -l)
+  if [ "$NUMCABALS" -gt 1 ]; then
+    echo "Error: Found multiple cabal files in $(pwd)"
+    exit 1
+  fi
+  local REALCABAL=$(basename "$(ls ./*.cabal)")
+  (cat "$REALCABAL" | sed 's/--.*$//' | unconstrainCabal) > cabbageDummy.cabal
+  mv "$REALCABAL" cabbageBackup.bak
+  mv cabbageDummy.cabal "$REALCABAL"
+  freezeCabbagePatch
+  local OK=$?
+  return $OK
+}
+
 # List directories of added sources
 getAddedSources() {
   sed '1,/^$/ d' | sed '/^$/,$ d'
@@ -173,12 +342,59 @@ freezeWithConstraints() {
   local REALCABAL=$(basename "$(ls ./*.cabal)")
   ({ (isolateAndCleanupConstraints < "$1"); echo "***"; cat "$REALCABAL"; } \
    | pinBuildDepends) > cabbageDummy.cabal
+
+  # Remove cabbage-patch version suffixes so cabal freeze can work
+  sed 's/\( ==[[:digit:].]*\).4552/\1/' cabbageDummy.cabal > cabbageDummy2.cabal
+  rm cabbageDummy.cabal
   mv "$REALCABAL" cabbageBackup.bak
-  cabal freeze
+  freezeCabbagePatch
   local OK=$?
   mv cabbageBackup.bak "$REALCABAL"
-  rm cabbageDummy.cabal
+  rm cabbageDummy2.cabal
   return $OK
+}
+
+# Prints the extra-libraires from a cabal file iff they occur in a
+# library target.
+cabalExtraLibraries() {
+  cat ./*.cabal | isolateLibraryTarget | removeWindowsBlocks | \
+  grep -i "extra-libraries" | awk 'BEGIN { FS=":"; } { print($2); }'
+}
+
+# Looks in a cabal.config file to identify all dependencies, then
+# visits each of them in the .cabbages directory and prints out all
+# extra-libraries.
+allExtraLibrariesAux() {
+  local DEPS=($(getDependencies cabal.config))
+  local d
+  cabalExtraLibraries
+  (cd .cabbages && \
+   for d in "${DEPS[@]}"; do
+     (cd "$d" &&  cabalExtraLibraries)
+   done)
+}
+
+# Print out an array of possibly-needed extra-libraries.
+allExtraLibraries() {
+  local LIBS=($(allExtraLibrariesAux | sed 's/,/\
+/' | uniq))
+  echo "${LIBS[@]}"
+}
+
+# Let the user know they might need to prepare system dependencies.
+warnExtraLibraries() {
+  local LIBS=($(allExtraLibraries))
+  if [ "${#LIBS[@]}" -gt 0 ]; then
+    echo
+    echo "You may need to supply system dependencies!"
+    echo
+    echo "See the cabbage documentation for how to do this with a 'systemDeps'"
+    echo "section in a cabbage.config file."
+    echo
+    echo "Potentially necessary extra-libraries: ${LIBS[@]}"
+    read -p "Press any key to continue..." -n 1 -t 5
+    echo
+  fi
 }
 
 # Unversion package name. Remove the version number from a versioned
@@ -417,7 +633,8 @@ callCabbages() {
 
 # Build a .nix file from a .cabal file in the current directory Takes
 # the ghcPlatform string, this package's name, and whether or not this
-# package should define frozenCabbages.
+# package should define frozenCabbages: 0 = this is an upstream
+# package, 1 = this is a downstream package, 2 = this is a build-tool.
 mkCabbage() {
   local NIX
   local FROZENUPSTREAM
@@ -432,8 +649,8 @@ mkCabbage() {
     DEPNAMES[$i]=$(sed 's/\(.*\)-[[:digit:]].*/\1/' <<< "${DEPS[$i]}")
   done
 
-  if [ "$3" = true ]; then
-    # This is /the/ downstream package
+  if [ $3 -gt 0 ]; then
+    # This is /the/ downstream package or a build-tool
 
     # We will need the standard callPackage function
     FROZENUPSTREAM="callPackage"
@@ -477,9 +694,29 @@ EOF
     SYSTEMDEPS=""
   fi
 
+  local TOOLS=($(allBuildTools))
+  local TOOLSDEPS=""
+  if [ "${#TOOLS[@]}" -gt 0 ]; then
+    TOOLSDEPS=$(echo "${TOOLS[@]}" | awk '{for(i=1;i<=NF;i++) printf(", %s",$(i));}')
+  fi
+
+  local FRAMEWORKS=($(cabalFrameworks))
+  local NIXLD
+  if [ "${#FRAMEWORKS[@]}" -gt 0 ]; then
+    local fw
+    NIXLD="\
+  NIX_LDFLAGS = lib.optionalString stdenv.isDarwin \""
+    for fw in "${FRAMEWORKS[@]}"; do
+      NIXLD="$NIXLD -framework $fw"
+    done
+    NIXLD="$NIXLD\";"
+  else
+    NIXLD=""
+  fi
+
   # Now we build up the Nix expression
   IFS=$'\n' read -r -d '' NIX <<EOF
-{ stdenv, lib, haskellBuildTools, pkgs, $FROZENUPSTREAM }:
+{ stdenv, lib, haskellBuildTools, pkgs$TOOLSDEPS, $FROZENUPSTREAM }:
 let cabalTmp = "cabal --config-file=./.cabal/config";
     $FROZENDEF
     mkCmd = pkg: let nm = lib.strings.removePrefix "haskell-" pkg.name;
@@ -487,13 +724,15 @@ let cabalTmp = "cabal --config-file=./.cabal/config";
                      pkgPath = ".cabal-sandbox/$1-packages.conf.d";
                  in ''ln -sFf \${p}/\${pkgPath}/*.conf \$out/\${pkgPath}/
                     '';
-    mkSetupCmd = pkg: let nm = lib.strings.removePrefix "haskell-" pkg.name;
-                          p = pkg.outPath;
-                      in "$LINKSANDBOX";
+$(if [ $3 -gt 0 ]; then
+    echo "    mkSetupCmd = pkg: let nm = lib.strings.removePrefix \"haskell-\" pkg.name;"
+    echo "                          p = pkg.outPath;"
+    echo "                      in \"$LINKSANDBOX\";"
+  fi)
 in
 stdenv.mkDerivation rec {
   name = "haskell-$2";
-  src = $(if [ "$3" = true ]; then 
+  src = $(if [ $3 -eq 1 ]; then 
             echo "./dist/$2.tar.gz"
           else
             echo "./."
@@ -501,13 +740,14 @@ stdenv.mkDerivation rec {
   cabbageDeps = with frozenCabbages; [ $(echo "${DEPNAMES[@]}") ];
   systemDeps = (with pkgs; [ $SYSTEMDEPS ]) ++
                lib.lists.unique (lib.concatMap (lib.attrByPath ["systemDeps"] []) cabbageDeps);
-  propagatedBuildInputs = systemDeps;
-  buildInputs = [ stdenv.cc ] ++ haskellBuildTools ++ cabbageDeps ++ systemDeps;
+  propagatedBuildInputs = systemDeps;$NIXLD
+  buildInputs = [ stdenv.cc $(echo "${TOOLS[@]}")] ++ haskellBuildTools ++ cabbageDeps ++ systemDeps;
 
   # Build the commands to merge package databases
   cmds = lib.strings.concatStrings (map mkCmd cabbageDeps);
+$(if [ $3 -gt 0 ]; then
+    cat << SETUPEOF
   setupCmds = lib.strings.concatStrings (map mkSetupCmd cabbageDeps);
-
   setup = builtins.toFile "setup.sh" ''
     
     # Takes a GHC platform string, an array of add-source dependency
@@ -521,11 +761,15 @@ stdenv.mkDerivation rec {
       for ((i = 0; i < "''\${#DEPS[@]}"; ++i)); do
         STAMPED[\$i]="(\"''\${DEPS[\$i]}\",\$CUR_TIME)"
       done
-      local NEWSTAMP="(\"\$1\",[''\${STAMPED[@]}])"
+      local LIST=\$(printf ",%s" "''\${STAMPED[@]}")
+      LIST=''\${LIST:1}
+      local NEWSTAMP="(\"\$1\",[\$LIST])"
       if echo "\$3" | grep -q "\$1"; then
         echo "\$3" | sed "s:(\"\$1\",[^]]*\]):\$NEWSTAMP:"
+      elif echo "\$3" | grep -q "]\\\\$"; then
+        echo "\$3" | sed "s:\]\\\$:,\$NEWSTAMP]:"
       else
-        echo "\$3" | sed "s:\]\\\$:\$NEWSTAMP]:"
+        echo "[\$NEWSTAMP]"
       fi
     }
     eval "\$setupCmds"
@@ -534,6 +778,8 @@ stdenv.mkDerivation rec {
     OLDTIMESTAMPS=\$(cat .cabal-sandbox/add-source-timestamps)
     updateTimeStamps "$1" SRCS[@] "\$OLDTIMESTAMPS" > .cabal-sandbox/add-source-timestamps
   '';
+SETUPEOF
+  fi)
 
   builder = builtins.toFile "builder.sh" ''
     source \$stdenv/setup
@@ -568,7 +814,12 @@ EOF
   echo "$NIX" > default.nix
 }
 
+# Freezes the cabal file in the current directory. Takes the versioned
+# name of the package to prepare, and the dbPath for the current
+# platform (e.g. x86_64-osx-ghc-7.8.4).
 prepCabbage() {
+  local d="$1"
+  local dbPath="$2"
   if [ -f cabbage.config ]; then
     local MYNAME=$(unversionPackageName "$d")
     local FLAGS=$(cat cabbage.config | flagsFor "$MYNAME")
@@ -577,6 +828,7 @@ prepCabbage() {
       fixAllFlags "$FLAGS"
     fi
   fi
+  cabal sandbox init --sandbox=../../.cabal-sandbox > /dev/null
   freezeCabbagePatch > /dev/null
   if ! [ $? -eq 0 ]; then
     freezeWithConstraints ../../cabal.config
@@ -584,18 +836,22 @@ prepCabbage() {
     mv cabal.config cabal.config.bak
     updateConstraintsAwk ../../cabal.config cabal.config.bak > cabal.config
   fi
-  mkCabbage "$dbPath" "$d" false
+  rm cabal.sandbox.config
+  mkCabbage "$dbPath" "$d" 0
 }
 
 # Takes a flag to determine if the dependencies of all targets should
 # be built. If the flag is true, then the build-depends of all targets
-# are consolidated and considered when determining a build plan.
+# are consolidated and considered when determining a build plan. The
+# second argument is another flag for which true indicates this is a
+# downstream package, and false indicates this is a build-tool.
 mkCabbages() {
   local NUMCABALS=$(find . -maxdepth 1 -name '?*.cabal' | wc -l)
   if [ "$NUMCABALS" -gt 1 ]; then
     echo "Error: Found multiple cabal files in $(pwd)!"
     exit 1
   fi
+
   local CABAL=$(basename "$(ls ./*.cabal)")
   if [ -f cabbage.config ]; then
     local MYVNAME=$(getMyFullName)
@@ -611,6 +867,12 @@ mkCabbages() {
     freezeConsolidatedCabal ./*.cabal
   else
     freezeCabbagePatch
+    if ! [ $? -eq 0 ]; then
+      if [ "$2" = false ]; then
+        echo "Trying emergency constraint patch..."
+        freezeUnconstrained
+      fi
+    fi
   fi
   if [ -f "$CABAL.cabbage.bak" ]; then
     mv "$CABAL.cabbage.bak" "$CABAL"
@@ -627,14 +889,40 @@ mkCabbages() {
   if [ -f cabbage.config ]; then
     cat cabbage.config | sowFlags
   fi
+
+  # Print a message if there are extra-libraries sepecified in any
+  # .cabal file used to build the downstream package that is not
+  # obviously guarded by an os(windows) or os(solaris) check.
+  warnExtraLibraries
+
   pushd .cabbages > /dev/null
+  local d
   for d in "${deps[@]}"; do
     echo "Making cabbage: $d"
-    (cd "$d" && prepCabbage)
+    (cd "$d" && prepCabbage "$d" "$dbPath")
   done
   popd > /dev/null
+
+  local BUILDTOOLS=($(allBuildableBuildTools))
+
+  if [ "${#BUILDTOOLS}" -gt 0 ]; then
+    echo "Making cabbages for build-tools"
+    pushd .cabbages > /dev/null
+    local bt
+    for bt in "${BUILDTOOLS[@]}"; do
+      cabal get "$bt"
+      local d=$(basename $(find . -name "$bt-[[:digit:].]*" -depth 1))
+      echo "Making build-tool cabbage: $d"
+      (cd "$d" && cabal sandbox init && mkCabbages false false)
+    done
+    popd > /dev/null
+  fi
   
-  mkCabbage "$dbPath" "$(getMyFullName)" true
+  if [ "$2" = true ]; then
+    mkCabbage "$dbPath" "$(getMyFullName)" 1
+  else
+    mkCabbage "$dbPath" "$(getMyFullName)" 2
+  fi
 }
 
 testBenchExecutable() {
@@ -746,10 +1034,10 @@ getReinstallableGlobals() {
 # Freeze a cabal package, then tweak the ~cabal.config~ file to
 # cabbage patch references to globally installed packages.
 freezeCabbagePatch() {
-  cabal freeze
-  mv cabal.config cabal.config.bak
-  ((getReinstallableGlobals; cat cabal.config.bak) | cabbagePatchConfig) > cabal.config
-  rm cabal.config.bak
+  cabal freeze && \
+    mv cabal.config cabal.config.bak && \
+    ((getReinstallableGlobals; cat cabal.config.bak) | cabbagePatchConfig) > cabal.config && \
+    rm cabal.config.bak
 }
 
 # Takes a versioned file name, e.g. "foo-0.8.2",
@@ -794,15 +1082,34 @@ getCabalFile() {
 
 # A default Nix expression suitable for nix-shell or installation.
 defaultShell() {
+  local TOOLS=($(allBuildableBuildTools))
+
+  local TOOLSDEPS
+  if [ "${#TOOLS[@]}" -gt 0 ]; then
+    TOOLSDEPS=$(echo " ${TOOLS[@]}")
+  else
+    TOOLSDEPS=""
+  fi
   local NIX
-  IFS=$'\n' read -r -d '' NIX <<'EOF'
-let pkgs = import <nixpkgs> {}; in
-pkgs.callPackage ./default.nix {
-   inherit pkgs;
-   haskellBuildTools = with pkgs;
-                       [ ghc.ghc784
-                         haskellPackages.cabalInstall_1_20_0_6
-                         haskellPackages.happy ];
+  IFS=$'\n' read -r -d '' NIX <<EOF
+let pkgs = import <nixpkgs> {};
+    haskellBuildTools = with pkgs;
+                        [ ghc.ghc784
+                          haskellPackages.cabalInstall_1_20_0_6 ];
+    happy = pkgs.haskellngPackages.happy;
+    alex = pkgs.haskellngPackages.alex;
+    callPackage = pkgs.lib.callPackageWith (pkgs // {inherit happy alex callPackage$TOOLSDEPS;});
+$(if [ "${#TOOLS[@]}" -gt 0 ]; then
+    local t
+    for t in "${TOOLS[@]}"; do
+      local buildTool=$(basename $(find .cabbages -name "$t-[[:digit:].]*" -depth 1))
+      echo "    $t = callPackage .cabbages/$buildTool/default.nix {"
+      echo "      inherit pkgs haskellBuildTools;"
+      echo "    };"
+    done
+  fi)
+in callPackage ./default.nix {
+   inherit pkgs haskellBuildTools;
 }
 EOF
   echo "$NIX"
@@ -863,16 +1170,16 @@ if [ "$#" -eq 0 ]; then
   if ! [ -f cabal.sandbox.config ]; then
     cabal sandbox init
   fi
+  mkCabbages $ALLTARGETS true
   if ! [ -f shell.nix ]; then
     defaultShell > shell.nix
   fi
-  mkCabbages $ALLTARGETS
 else
   mytmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'cabbage-temp')
   (cd "$mytmpdir" \
       && getCabalFile "$1" \
       && cabal sandbox init \
-      && mkCabbages $ALLTARGETS \
+      && mkCabbages $ALLTARGETS true \
       && defaultShell > shell.nix \
       && cabal sandbox hc-pkg recache \
       && nix-shell --command "echo 'Done'" \
